### ISSUE TITLE
Enhance Los Angeles Lakers Theme with Active View Colors

### ISSUE THREAD

**Issue by coder-ralph** [coder-ralph/lakers-vscode-theme#1]
# Tasks:

- [ ] Add active border and background colors for activity bar items.
- [ ] Update sidebar title, tab, and status bar colors for active and inactive states.
- [ ] Enhance title bar colors to improve visibility of active/inactive states.
